# Generated by Django 5.2.7 on 2025-10-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('idno', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('admitteddatetime', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
