# Generated by Django 5.2.7 on 2025-10-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareConnectapp', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
